language: node_js
node_js:
  - "10"
before_deploy:
  - git submodule update --init --recursive
  - yarn install --frozen-lockfile --network-concurrency 1
  - yarn generate-rules
  - cd firebase
deploy:
  on: staging
  provider: firebase
  token:
    secure: Ue3tILUUSDEmfIgvX2e9s3IfMLZQfF5dotkQC/PY+6pRogez2D1R1kppwPy0++9docM+ItcxBdYvrd/7yKEaXbmPMi5cx+KC67KlFKvBvGzsW7T0HMnmQKWzr8AIVXCKBna5oH31bavCuNJguStNM8M7GzESMMkciH97LpEjgB+27I0tVI27HrVHqKB9c6/Kbmw+CMkEWBpjQ7WxNInrWfQsJeBaaOGPwXGMhSeGTWduwIm2c+w0v/SRcl3ytyvi3NCE84OSnlxNy2yVyuklv513lco8yphTuiwWcbM+hG2npf5zEky1XCbwHF3f8dfzFCqTljh9rkbaQNXOhZpVy+nT7TlEOWeFFcSfzpoMnArh2QM/YUIOjlxz0UzW9atz2TFH3+2oYSVhVzHm5LATAgGnov+7B1H3dHgq3Qs/tlmIotPy25byPMrkvqqhpRp87uSXaimPoy/7RNWEzYRSC1jM/hFWpD8v6jng53yRMd4ptmWz8FJPv8go1qeuvYTrU7rgXPkAbiFzS/Y5mh+XnkBtJne9UuZgEJjmP76L/KPoCFs6zOr2F9gZTxp5rDNZVfnbJoXbVmWFNT6+TxDYIu+JWPMkwLlIvYmgA1bZ1PE7nG04p+jmcXd8wRolW8RFpsoUdFjWNhlvFUdAzLnAgOFBIJw/y9sFZFSnfsN0yE4=
  project: WorldBrain-Staging
